### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by juliankrispel** [juliankrispel/zettel#14]

**Comment by qubyte** [comment]
The workflows approach I've used in #17 can be applied to CI too.
Simple example: https://github.com/qubyte/mixomatic/blob/master/.github/workflows/ci.yml
More complex example: https://github.com/qubyte/fetch-ponyfill/blob/master/.github/workflows/ci.yml

You can see the latter in action by clicking on "View details" [here](https://github.com/qubyte/fetch-ponyfill/pull/222).
