### ISSUE TITLE
Handle Input Events from Android devices

### ISSUE THREAD

**Issue by juliankrispel** [juliankrispel/zettel#2]
[Input Level 2](https://www.w3.org/TR/input-events-2/)
[Trix support for Input Level 2](https://github.com/basecamp/trix/pull/580)

**Comment by juliankrispel** [comment]
So I got myself a pixel but I'm currently [blocked by this](https://support.google.com/chrome/thread/15368759?hl=en), waiting for the next chrome canary release

**Comment by codex-zaydek** [comment]
Hey Julian — I wanted to share my approach for testing for Android. I downloaded Android Studio (on my Mac) and setup a virtual Pixel device in the ‘Open AVD Manager’ settings. I then iterated closely on both my local web browser and the virtual device.

It’s not as good as the real thing but I found it answered a lot of previously unanswered questions. Let me know if you want any more details on this approach.
